import argparse

from sqlalchemy import delete, select

from app.database import SessionLocal
from app.models.complaint import Complaint, ComplaintStatus
from app.schemas.complaint import ComplaintCreate, ComplaintUpdate
from app.services.complaint_service import create_complaint, update_complaint


SEED_COMPLAINTS = [
    {
        "originalText": "Garbage is blocking the drain near Madhapur Metro.",
        "normalizedEnglishText": "Garbage is blocking the drain near Madhapur Metro.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "SANITATION",
        "subcategory": "GARBAGE_BLOCKING_DRAIN",
        "department": "MULTI_DEPARTMENT",
        "priority": "HIGH",
        "latitude": 17.4483,
        "longitude": 78.3915,
        "landmark": "Near Madhapur Metro",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "analysisSource": "MANUAL",
        "requiresHumanVerification": True,
        "status": "UNDER_REVIEW",
        "assignedTeam": "Ward 107 Sanitation Crew",
    },
    {
        "originalText": "Madhapur metro దగ్గర garbage dump అయింది",
        "normalizedEnglishText": "Garbage has accumulated near Madhapur Metro.",
        "originalLanguage": "te",
        "detectedLanguage": "te",
        "category": "SANITATION",
        "subcategory": "GARBAGE_ACCUMULATION",
        "department": "SANITATION",
        "priority": "MEDIUM",
        "latitude": 17.4479,
        "longitude": 78.3921,
        "landmark": "Madhapur Metro Gate B",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "ASSIGNED",
        "assignedTeam": "Ward 107 Sanitation Crew",
    },
    {
        "originalText": "Waste pile outside Madhapur police station.",
        "normalizedEnglishText": "Waste has piled up outside Madhapur police station.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "SANITATION",
        "subcategory": "GARBAGE_ACCUMULATION",
        "department": "SANITATION",
        "priority": "MEDIUM",
        "latitude": 17.4486,
        "longitude": 78.3896,
        "landmark": "Madhapur police station",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Kachra spread near Image Hospital road Madhapur.",
        "normalizedEnglishText": "Garbage is spread near Image Hospital road Madhapur.",
        "originalLanguage": "hi",
        "detectedLanguage": "hi",
        "category": "SANITATION",
        "subcategory": "GARBAGE_ACCUMULATION",
        "department": "SANITATION",
        "priority": "LOW",
        "latitude": 17.4472,
        "longitude": 78.3908,
        "landmark": "Image Hospital road",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Road pe bahut waterlogging hai near Gachibowli signal",
        "normalizedEnglishText": "There is waterlogging near Gachibowli signal.",
        "originalLanguage": "hi",
        "detectedLanguage": "hi",
        "category": "WATERLOGGING",
        "subcategory": "ROAD_WATERLOGGING",
        "department": "DRAINAGE",
        "priority": "HIGH",
        "latitude": 17.4401,
        "longitude": 78.3489,
        "landmark": "Gachibowli signal",
        "locality": "Gachibowli",
        "wardName": "Gachibowli",
        "wardNumber": 105,
        "status": "IN_PROGRESS",
        "assignedTeam": "Stormwater Response Team",
    },
    {
        "originalText": "Drain blocked beside Gachibowli signal bus stop.",
        "normalizedEnglishText": "A drain is blocked beside Gachibowli signal bus stop.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "DRAINAGE",
        "subcategory": "BLOCKED_DRAIN",
        "department": "DRAINAGE",
        "priority": "HIGH",
        "latitude": 17.4405,
        "longitude": 78.3494,
        "landmark": "Gachibowli signal bus stop",
        "locality": "Gachibowli",
        "wardName": "Gachibowli",
        "wardNumber": 105,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "నాలా overflow అవుతోంది near Gachibowli signal",
        "normalizedEnglishText": "The drain is overflowing near Gachibowli signal.",
        "originalLanguage": "te",
        "detectedLanguage": "te",
        "category": "DRAINAGE",
        "subcategory": "DRAIN_OVERFLOW",
        "department": "DRAINAGE",
        "priority": "HIGH",
        "latitude": 17.4397,
        "longitude": 78.3485,
        "landmark": "Near Gachibowli signal",
        "locality": "Gachibowli",
        "wardName": "Gachibowli",
        "wardNumber": 105,
        "status": "ASSIGNED",
        "assignedTeam": "Drainage Crew Gachibowli",
    },
    {
        "originalText": "Stagnant water outside Gachibowli stadium service lane.",
        "normalizedEnglishText": "There is stagnant water outside Gachibowli stadium service lane.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATERLOGGING",
        "subcategory": "STAGNANT_WATER",
        "department": "DRAINAGE",
        "priority": "MEDIUM",
        "latitude": 17.4410,
        "longitude": 78.3491,
        "landmark": "Gachibowli stadium service lane",
        "locality": "Gachibowli",
        "wardName": "Gachibowli",
        "wardNumber": 105,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Large pothole on the service road near Cyber Towers, Hitech City.",
        "normalizedEnglishText": "There is a large pothole on the service road near Cyber Towers, Hitech City.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "ROADS",
        "subcategory": "POTHOLE",
        "department": "ROADS",
        "priority": "HIGH",
        "latitude": 17.4505,
        "longitude": 78.3804,
        "landmark": "Cyber Towers",
        "locality": "Hitech City",
        "wardName": "Hitech City",
        "wardNumber": 106,
        "status": "ASSIGNED",
        "assignedTeam": "Road Repair Unit 2",
    },
    {
        "originalText": "Broken road patch near Shilparamam Hitech City.",
        "normalizedEnglishText": "There is a broken road patch near Shilparamam Hitech City.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "ROADS",
        "subcategory": "ROAD_DAMAGE",
        "department": "ROADS",
        "priority": "MEDIUM",
        "latitude": 17.4510,
        "longitude": 78.3811,
        "landmark": "Near Shilparamam",
        "locality": "Hitech City",
        "wardName": "Hitech City",
        "wardNumber": 106,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Pothole near Cyber Gateway entry road.",
        "normalizedEnglishText": "There is a pothole near Cyber Gateway entry road.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "ROADS",
        "subcategory": "POTHOLE",
        "department": "ROADS",
        "priority": "HIGH",
        "latitude": 17.4500,
        "longitude": 78.3799,
        "landmark": "Cyber Gateway entry road",
        "locality": "Hitech City",
        "wardName": "Hitech City",
        "wardNumber": 106,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Street light not working near Ameerpet metro entrance.",
        "normalizedEnglishText": "A street light is not working near Ameerpet metro entrance.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "STREET_LIGHTS",
        "subcategory": "BROKEN_STREET_LIGHT",
        "department": "ELECTRICAL",
        "priority": "LOW",
        "latitude": 17.4355,
        "longitude": 78.4482,
        "landmark": "Ameerpet metro entrance",
        "locality": "Ameerpet",
        "wardName": "Ameerpet",
        "wardNumber": 98,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Water pressure is very low in Jubilee Hills Road No. 36.",
        "normalizedEnglishText": "Water pressure is very low in Jubilee Hills Road No. 36.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATER_SUPPLY",
        "subcategory": "LOW_PRESSURE",
        "department": "WATER_SUPPLY",
        "priority": "MEDIUM",
        "latitude": 17.4308,
        "longitude": 78.4098,
        "landmark": "Jubilee Hills Road No. 36",
        "locality": "Jubilee Hills",
        "wardName": "Jubilee Hills",
        "wardNumber": 95,
        "status": "ASSIGNED",
        "assignedTeam": "Water Board Zone C",
    },
    {
        "originalText": "چارمینار کے قریب کچرا جمع ہے",
        "normalizedEnglishText": "Garbage has accumulated near Charminar.",
        "originalLanguage": "ur",
        "detectedLanguage": "ur",
        "category": "SANITATION",
        "subcategory": "GARBAGE_ACCUMULATION",
        "department": "SANITATION",
        "priority": "MEDIUM",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "landmark": "Near Charminar",
        "locality": "Charminar",
        "wardName": "Charminar",
        "wardNumber": 49,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Open drain cover missing beside Begumpet flyover.",
        "normalizedEnglishText": "A drain cover is missing beside Begumpet flyover.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "DRAINAGE",
        "subcategory": "OPEN_DRAIN",
        "department": "DRAINAGE",
        "priority": "EMERGENCY",
        "latitude": 17.4447,
        "longitude": 78.4665,
        "landmark": "Beside Begumpet flyover",
        "locality": "Begumpet",
        "wardName": "Begumpet",
        "wardNumber": 149,
        "status": "IN_PROGRESS",
        "assignedTeam": "Emergency Drainage Crew",
    },
    {
        "originalText": "Traffic signal is not working near Secunderabad station.",
        "normalizedEnglishText": "The traffic signal is not working near Secunderabad station.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "TRAFFIC",
        "subcategory": "SIGNAL_NOT_WORKING",
        "department": "TRAFFIC",
        "priority": "HIGH",
        "latitude": 17.4344,
        "longitude": 78.5011,
        "landmark": "Near Secunderabad station",
        "locality": "Secunderabad",
        "wardName": "Secunderabad",
        "wardNumber": 150,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Kukatpally metro దగ్గర garbage చాలా ఉంది",
        "normalizedEnglishText": "There is a lot of garbage near Kukatpally Metro.",
        "originalLanguage": "te",
        "detectedLanguage": "te",
        "category": "SANITATION",
        "subcategory": "GARBAGE_ACCUMULATION",
        "department": "SANITATION",
        "priority": "MEDIUM",
        "latitude": 17.4933,
        "longitude": 78.4013,
        "landmark": "Near Kukatpally Metro",
        "locality": "Kukatpally",
        "wardName": "Kukatpally",
        "wardNumber": 121,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Garbage is blocking the drain near Kukatpally Metro.",
        "normalizedEnglishText": "Garbage is blocking the drain near Kukatpally Metro.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "SANITATION",
        "subcategory": "GARBAGE_BLOCKING_DRAIN",
        "department": "MULTI_DEPARTMENT",
        "priority": "HIGH",
        "latitude": 17.49355,
        "longitude": 78.40155,
        "landmark": "Kukatpally Metro Gate 1",
        "locality": "Kukatpally",
        "wardName": "Kukatpally",
        "wardNumber": 121,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Waste has piled beside the drainage line near Kukatpally station.",
        "normalizedEnglishText": "Waste has piled beside the drainage line near Kukatpally station.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "SANITATION",
        "subcategory": "GARBAGE_BLOCKING_DRAIN",
        "department": "MULTI_DEPARTMENT",
        "priority": "HIGH",
        "latitude": 17.4937,
        "longitude": 78.40145,
        "landmark": "Kukatpally station drainage line",
        "locality": "Kukatpally",
        "wardName": "Kukatpally",
        "wardNumber": 121,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Garbage heap outside Kukatpally Metro is clogging the drain.",
        "normalizedEnglishText": "Garbage heap outside Kukatpally Metro is clogging the drain.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "SANITATION",
        "subcategory": "GARBAGE_BLOCKING_DRAIN",
        "department": "MULTI_DEPARTMENT",
        "priority": "HIGH",
        "latitude": 17.49345,
        "longitude": 78.40165,
        "landmark": "Outside Kukatpally Metro",
        "locality": "Kukatpally",
        "wardName": "Kukatpally",
        "wardNumber": 121,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Waterlogging near Madhapur Metro entrance.",
        "normalizedEnglishText": "Waterlogging near Madhapur Metro entrance.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATERLOGGING",
        "subcategory": "ROAD_WATERLOGGING",
        "department": "DRAINAGE",
        "priority": "MEDIUM",
        "latitude": 17.44815,
        "longitude": 78.39165,
        "landmark": "Madhapur Metro entrance",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Road flooded outside Madhapur Metro station.",
        "normalizedEnglishText": "Road flooded outside Madhapur Metro station.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATERLOGGING",
        "subcategory": "ROAD_WATERLOGGING",
        "department": "DRAINAGE",
        "priority": "HIGH",
        "latitude": 17.44805,
        "longitude": 78.39135,
        "landmark": "Outside Madhapur Metro station",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Rainwater accumulated near Madhapur Metro gate.",
        "normalizedEnglishText": "Rainwater accumulated near Madhapur Metro gate.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATERLOGGING",
        "subcategory": "ROAD_WATERLOGGING",
        "department": "DRAINAGE",
        "priority": "MEDIUM",
        "latitude": 17.44825,
        "longitude": 78.39185,
        "landmark": "Madhapur Metro gate",
        "locality": "Madhapur",
        "wardName": "Madhapur",
        "wardNumber": 107,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Pipeline leak outside Botanical Garden gate.",
        "normalizedEnglishText": "There is a pipeline leak outside Botanical Garden gate.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATER_SUPPLY",
        "subcategory": "PIPELINE_LEAK",
        "department": "WATER_SUPPLY",
        "priority": "HIGH",
        "latitude": 17.4568,
        "longitude": 78.3632,
        "landmark": "Outside Botanical Garden gate",
        "locality": "Kondapur",
        "wardName": "Kondapur",
        "wardNumber": 104,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Mosquito breeding in stagnant water near Mehdipatnam bus stop.",
        "normalizedEnglishText": "Mosquito breeding is reported in stagnant water near Mehdipatnam bus stop.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "PUBLIC_HEALTH",
        "subcategory": "MOSQUITO_BREEDING",
        "department": "PUBLIC_HEALTH",
        "priority": "HIGH",
        "latitude": 17.3958,
        "longitude": 78.4392,
        "landmark": "Mehdipatnam bus stop",
        "locality": "Mehdipatnam",
        "wardName": "Mehdipatnam",
        "wardNumber": 70,
        "status": "SUBMITTED",
    },
    {
        "originalText": "Water tanker spillage causing slippery road near Tolichowki.",
        "normalizedEnglishText": "Water spillage is causing a slippery road near Tolichowki.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "OTHER",
        "subcategory": "MISCELLANEOUS",
        "department": "MANUAL_REVIEW",
        "priority": "LOW",
        "latitude": 17.3984,
        "longitude": 78.4131,
        "landmark": "Tolichowki main road",
        "locality": "Tolichowki",
        "wardName": "Tolichowki",
        "wardNumber": 68,
        "status": "SUBMITTED",
    },
    {
        "originalText": "No water supply since morning near Miyapur X roads.",
        "normalizedEnglishText": "There has been no water supply since morning near Miyapur X roads.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "WATER_SUPPLY",
        "subcategory": "NO_WATER",
        "department": "WATER_SUPPLY",
        "priority": "MEDIUM",
        "latitude": 17.4967,
        "longitude": 78.3619,
        "landmark": "Miyapur X roads",
        "locality": "Miyapur",
        "wardName": "Miyapur",
        "wardNumber": 108,
        "status": "ASSIGNED",
    },
    {
        "originalText": "Street dogs and garbage near Tarnaka market entrance.",
        "normalizedEnglishText": "Garbage and public health concerns are reported near Tarnaka market entrance.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "PUBLIC_HEALTH",
        "subcategory": "PUBLIC_HEALTH_CONCERN",
        "department": "PUBLIC_HEALTH",
        "priority": "MEDIUM",
        "latitude": 17.4286,
        "longitude": 78.5382,
        "landmark": "Tarnaka market entrance",
        "locality": "Tarnaka",
        "wardName": "Tarnaka",
        "wardNumber": 143,
        "status": "UNDER_REVIEW",
    },
    {
        "originalText": "Broken median reflector on Banjara Hills Road No. 12.",
        "normalizedEnglishText": "A median reflector is broken on Banjara Hills Road No. 12.",
        "originalLanguage": "en",
        "detectedLanguage": "en",
        "category": "TRAFFIC",
        "subcategory": "ROAD_SAFETY",
        "department": "TRAFFIC",
        "priority": "LOW",
        "latitude": 17.4156,
        "longitude": 78.4347,
        "landmark": "Banjara Hills Road No. 12",
        "locality": "Banjara Hills",
        "wardName": "Banjara Hills",
        "wardNumber": 92,
        "status": "RESOLVED",
    },
]


def seed(reset: bool = False) -> None:
    db = SessionLocal()
    try:
        if reset:
            db.execute(delete(Complaint))
            db.commit()
        existing = db.scalar(select(Complaint.id).limit(1))
        if existing:
            print("Seed skipped: complaints already exist. Use --reset for development reseeding.")
            return
        for seed_item in SEED_COMPLAINTS:
            item = seed_item.copy()
            status = item.pop("status", "SUBMITTED")
            assigned_team = item.pop("assignedTeam", None)
            complaint = create_complaint(db, ComplaintCreate(**item))
            update_complaint(
                db,
                complaint.reference_id,
                ComplaintUpdate(status=ComplaintStatus(status), assignedTeam=assigned_team),
            )
        print(f"Seeded {len(SEED_COMPLAINTS)} complaints.")
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed Mana Hyderabad development data.")
    parser.add_argument("--reset", action="store_true", help="Delete existing complaints before seeding. Development only.")
    args = parser.parse_args()
    seed(reset=args.reset)
